### ISSUE TITLE
Some fix for clone

### ISSUE THREAD

**Issue by Negashev** [shpwrck/rancher-clusterapi-autoscaling#1]
on clone MachineDeployment

do not forget name:
```
metadata:
  labels:
    # objectset.rio.cattle.io/hash: 581f8260dac18d89c7f6a63e0e10f0dbfe0443 <- and remove `objectset.rio.cattle.io/hash`
  name: {{ INSERT NEW DEPLOYMENT NAME }} # <- set name
```
